# Generated by Django 4.1.7 on 2023-05-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videoname',
            field=models.CharField(max_length=500),
        ),
    ]
